apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  tssc/gitops: wi8jef387-go 
  janus-idp.io/tekton: wi8jef387-go
  backstage.io/kubernetes-id: wi8jef387-go
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: wi8jef387-go
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml